name = "subtitle-search"
main = "worker.ts"
compatibility_date = "2025-03-23"

[ai]
binding = "AI"

[[vectorize]]
binding = "SUBTITLE_INDEX"
index_name = "vv-search"

[observability.logs]
enabled = true